language: python
python:
  - "3.6"
  # https://github.com/travis-ci/travis-ci/issues/9815
  #- "3.7-dev"

install:
  - python setup.py develop
  - pip install -r requirements-dev.txt

script:
  - make lint
  - make test
